YakimaAsrsWeb/Controllers/WCSController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YakimaAsrsWeb.Filters;

namespace YakimaAsrsWeb.Controllers
{
    [CustomAuthenticationFilter]
    public class WCSController : Controller
    {
        Service.WcsCrnService CrnService = new Service.WcsCrnService();
        Service.WcsTrkService TrkService = new Service.WcsTrkService();
        Service.WcsDeviceService DeviceService = new Service.WcsDeviceService();

        // GET: WCS_CRN
        public ActionResult VwCrn()
        {

            return View();
        }

        // GET: WCS_TRK
        public ActionResult VwTrk()
        {

            return View();
        }

        public ActionResult VwDevice()
        {

            return View();
        }

        public ActionResult VwStoreIn()
        {
            return View();
        }

        public ActionResult VwStoreOut()
        {
            return View();
        }

        public JsonResult GetWcsTrkData(string SearchText, int? AsrsID, int? Page, int? Limit)
        {
            Models.LayUITableData result = new Models.LayUITableData();
            var DataResult = TrkService.GetData();
            List<Models.WcsTrk> Trks = new List<Models.WcsTrk>();
            if (DataResult.IsCompleted)
            {
                if (DataResult.Result.Successed)
                {
                    foreach (System.Data.DataRow dr in DataResult.Result.Data.Rows)
                    {
                        Trks.Add(new Models.WcsTrk()
                        {
                            ASRS_ID = Convert.ToInt16(dr["ASRS_ID"]),
                            USE_CRN_ID = Convert.ToInt16(dr["USE_CRN_ID"]),
                            SER_NO = Convert.ToInt16(dr["SER_NO"]),
                            STEP = Convert.ToInt16(dr["STEP"]),
                            STATUS = Convert.ToInt16(dr["STATUS"]),
                            OPN = Convert.ToInt16(dr["OPN"]),
                            EMERGE = Convert.ToInt16(dr["EMERGE"]),
                            OPN_DESC = Convert.ToString(dr["OPN_DESC"]),
                            STATUS_DESC = Convert.ToString(dr["STATUS_DESC"]),
                            STEP_DESC = Convert.ToString(dr["STEP_DESC"]),
                            BIN_NO = Convert.ToString(dr["BIN_NO"]),
                            DEV_NO = Convert.ToString(dr["DEV_NO"]),
                            IO = Convert.ToString(dr["IO"]),
                            CREATE_BY = Convert.ToString(dr["CREATE_BY"]),
                            USER_NAME = Convert.ToString(dr["USER_NAME"]),
                            CUR_DEV_NO = Convert.ToString(dr["CUR_DEV_NO"]),
                            NEXT_DEV_NO = Convert.ToString(dr["NEXT_DEV_NO"]),
                            SIZE_CHK = Convert.ToInt16(dr["SIZE_CHK"]),
                            CREATE_DATE = Convert.ToDateTime(dr["CREATE_DATE"]).ToString("yyyy/MM/dd HH:mm:ss"),
                            IO_DESC = TrkService.GetIODesc(dr["IO"].ToString())
                        });
                    }

                    if (AsrsID.HasValue)
                    {
                        if (AsrsID > 0)
                            Trks = Trks.Where(o => o.ASRS_ID == AsrsID).ToList();
                    }
                    if (!string.IsNullOrEmpty(SearchText))
                    {
                        Trks = Trks.Where(o => o.IO.Contains(SearchText)
                        || o.IO_DESC.Contains(SearchText)
                        || o.STEP_DESC.Contains(SearchText)
                        || o.STATUS_DESC.Contains(SearchText)
                        || o.STEP.ToString().Contains(SearchText)
                        || o.STATUS.ToString().Contains(SearchText)
                        || o.USE_CRN_ID.ToString().Contains(SearchText)
                        || o.SER_NO.ToString().Contains(SearchText)
                        || o.USER_NAME.Contains(SearchText)
                        || o.ASRS_ID.ToString().Contains(SearchText)
                        ).ToList();
                    }
                    result.count = Trks.Count;

                    result.data = Trks;
                    result.code = 0;
                }
                else
                {
                    result.count = 0;

                    result.data = Trks;
                    result.code = Convert.ToInt16(HttpStatusCode.InternalServerError);
                }
            }
            result.data = Trks.Skip((Page.Value - 1) * Limit.Value).Take(Limit.Value);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetWcsDeviceData(string SearchText, int? AsrsID, int? Page, int? Limit)
        {
            Models.LayUITableData result = new Models.LayUITableData();
            var DataResult = DeviceService.GetData();
            List<Models.WcsDevice> Devices = new List<Models.WcsDevice>();
            if (DataResult.IsCompleted)
            {
                if (DataResult.Result.Successed)
                {
                    foreach (System.Data.DataRow dr in DataResult.Result.Data.Rows)
                    {
                        Devices.Add(new Models.WcsDevice()
                        {
                            ASRS_ID = Convert.ToInt16(dr["ASRS_ID"]),
                            DEST = Convert.ToString(dr["DEST"]),
                            DEV_NO = Convert.ToString(dr["DEV_NO"]),
                            SER_NO = Convert.ToInt16(dr["SER_NO"]),
                            MANU = Convert.ToInt16(dr["MANU"]) > 0 ? true : false,
                            AUTO = Convert.ToInt16(dr["AUTO"]) > 0 ? true : false,
                            AUTO_START = Convert.ToInt16(dr["AUTO_START"]) > 0 ? true : false,
                            ERR = Convert.ToInt16(dr["ERR"]) > 0 ? true : false,
                            IDLE = Convert.ToInt16(dr["IDLE"]) > 0 ? true : false,
                            LOAD = Convert.ToInt16(dr["LOAD"]) > 0 ? true : false,
                            STKIN_REQ = Convert.ToInt16(dr["STKIN_REQ"]) > 0 ? true : false,
                            IN_ENABLE = Convert.ToString(dr["IN_ENABLE"]),
                            OUT_ENABLE = Convert.ToString(dr["OUT_ENABLE"]),
                            IO_MODE = Convert.ToInt16(dr["IO_MODE"]),
                            WEIGHT = Convert.ToDecimal(dr["WEIGHT"]),
                            SIZE_CHK = Convert.ToDecimal(dr["SIZE_CHK"]),
                            OP_MODE = Convert.ToDecimal(dr["OP_MODE"]),
                            DISPLAY_ITEM = Convert.ToDecimal(dr["DISPLAY_ITEM"])
                        });
                    }

                    if (AsrsID.HasValue)
                    {
                        if (AsrsID > 0)
                            Devices = Devices.Where(o => o.ASRS_ID == AsrsID).ToList();
                    }
                    if (!string.IsNullOrEmpty(SearchText))
                    {
                        Devices = Devices.Where(o => o.DEV_NO.Contains(SearchText)
                        ).ToList();
                    }
                    result.count = Devices.Count;

                    result.data = Devices;
                    result.code = 0;
                }
                else
                {
                    result.count = 0;

                    result.data = Devices;
                    result.code = Convert.ToInt16(HttpStatusCode.InternalServerError);
                }
            }

            result.data= Devices.Skip((Page.Value - 1) * Limit.Value).Take(Limit.Value);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetWcsCrnData(string SearchText, int? Page, int? Limit)
        {
            Models.LayUITableData result = new Models.LayUITableData();
            var DataResult = CrnService.GetData();
            List<Models.WcsCrn> Crns = new List<Models.WcsCrn>();
            if (DataResult.IsCompleted)
            {
                if (DataResult.Result.Successed)
                {
                    foreach (System.Data.DataRow dr in DataResult.Result.Data.Rows)
                    {
                        Crns.Add(new Models.WcsCrn()
                        {
                            ASRS_ID = Convert.ToInt16(dr["ASRS_ID"]),
                            CRN_ID = Convert.ToInt16(dr["CRN_ID"]),
                            SER_NO = Convert.ToInt16(dr["SER_NO"]),
                            CRN_AUTO = Convert.ToBoolean(dr["CRN_AUTO"]),
                            CRN_ERROR = Convert.ToBoolean(dr["CRN_ERROR"]),
                            CRN_INITAL = Convert.ToBoolean(dr["CRN_INITAL"]),
                            CRN_READY = Convert.ToBoolean(dr["CRN_READY"]),
                            CRN_NO = Convert.ToString(dr["CRN_NO"]),
                            ERR_CODE = Convert.ToString(dr["ERR_CODE"]),
                            LOADING = Convert.ToBoolean(dr["LOADING"])
                        });
                    }
                    if (!string.IsNullOrEmpty(SearchText))
                    {
                        Crns = Crns.Where(o => o.CRN_NO.Contains(SearchText)).ToList();
                    }
                    result.count = Crns.Count;

                    result.data = Crns;
                    result.code = 0;
                }
                else
                {
                    result.count = 0;

                    result.data = Crns;
                    result.code = Convert.ToInt16(HttpStatusCode.InternalServerError);
                }
            }
            result.data = Crns.Skip((Page.Value - 1) * Limit.Value).Take(Limit.Value);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult PalletIn(Models.WcsTrk Item)
        {
            if (!ModelState.IsValid)

YakimaAsrsWeb/Views/WCS/VwCrn.cshtml
@{
    ViewBag.Title = "吊車狀態查詢維護";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<span class="layui-breadcrumb">
    @Html.ActionLink("首頁", "Index", "Home")
    <a><cite>作業管理</cite></a>
    <a><cite>@ViewBag.Title</cite></a>
</span>
<hr />

<div class="demoTable">
    
    <div class="layui-inline">
        <input class="layui-input" name="id" id="demoReload" placeholder="Crane ID" autocomplete="off">
    </div>
    <button class="layui-btn" data-type="reload">查詢</button>
</div>

<script type="text/html" id="checkboxTpl">
    <!-- 这里的 checked 的状态只是演示 -->
    <input type="checkbox" name="lock" value="{{d.CRN_ERROR}}" title="異常" lay-filter="lockDemo" {{ d.CRN_ERROR > 0 ? 'checked' : '' }} disabled="disabled">
</script>

<script type="text/html" id="barDemo">
    <a class="layui-btn layui-btn-xs" lay-event="edit">Command Resend</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">Reset</a>
</script>

<table class="layui-hide" id="LAY_table_user" lay-filter="WcsCrn"></table>


<script src="~/layui-v2.6.8/layui/layui.js"></script>
<script>
layui.use('table', function(){
  var table = layui.table;

  //方法级渲染
  table.render({
    elem: '#LAY_table_user'
      , url: '@Url.Action("GetWcsCrnData", "WCS")'
    ,cols: [[
      {field:'ASRS_ID', title: '倉庫ID', width:120, sort: true, fixed: true}
        , { field: 'CRN_ID', title: '吊車編號', width: 120, sort: true, fixed: true}
      ,{field:'SER_NO', title: '序號', width:80, sort: true}
      ,{field:'LOADING', title: '有載', width:80}
        , { field: 'CRN_AUTO', title: '自動', width: 80 }
        , { field: 'CRN_INITAL', title: '初始化', sort: true, width: 120 }
      ,{field:'CRN_READY', title: '準備就緒', sort: true, width:120}
        , { field: 'CRN_ERROR', title: '是否異常', sort: true, width: 120, templet: '#checkboxTpl'}
        , { field: 'ERR_CODE', title: '異常碼', width: 120 }
        , { fixed: 'right', title: '操作', toolbar: '#barDemo', width: 200 }
      
    ]]
    ,id: 'tbWcsCrn'
    ,page: true
    , limit: 15
    , limits: [15, 20, 25, 30]
    , curr: 1
    , height: 'full-210'
  });

    //监听行工具事件
    table.on('tool(WcsCrn)', function (obj) {
        var data = obj.data;
        
        //console.log(obj)
        if (obj.event === 'del') {
            layer.confirm('Reset Crane ' + data.CRN_ID + ' Confirm', function (index) {

                //Post Command
                $.ajax({
                 type: "POST",
                 url: "@Url.Action("CraneReset","WCS")",
                 data: JSON.stringify(data),
                    contentType: "application/json",
                    success: function (response) {
                        
                        JSON.stringify(response);
                        if (response.Successed) {
                            table.reload('tbWcsCrn', {
                                page: {
                                    curr: 1 //重新从第 1 页开始
                                }
                                , where: {
                                    SearchText: $('#demoReload').val()
                                }
                            });
                            layer.msg('Send reset command successed.');
                            layer.close(index);
                        }
                        else {
                            
                            layer.msg(response.Message, { icon: 5 });
                        }
                    },
                    failure: function (errMsg) {
                        alert(errMsg);
                    },
                    error: function (xhr, status, err) {
                        alert(err);
                    }
                })

                
            });
        } else if (obj.event === 'edit') {
            layer.prompt({
                formType: 2
                , value: data.email
            }, function (value, index) {
                obj.update({
                    email: value
                });
                layer.close(index);
            });
        }
    });

  var $ = layui.$, active = {
    reload: function(){
      var demoReload = $('#demoReload');

      //执行重载
        table.reload('tbWcsCrn', {
        page: {
          curr: 1 //重新从第 1 页开始
        }
        ,where: {
            SearchText: demoReload.val()
        }
      });
    }
  };

  $('.demoTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });

    
});
</script>

YakimaAsrsWeb/Views/WCS/VwDevice.cshtml
@{
    ViewBag.Title = "設備狀態查詢";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<span class="layui-breadcrumb">
    @Html.ActionLink("首頁", "Index", "Home")
    <a><cite>作業管理</cite></a>
    <a><cite>@ViewBag.Title</cite></a>
</span>
<hr />

<div class="demoTable">

    <div class="layui-form layui-input-inline">
        <select name="AsrsID" id="cbAsrsID">
            <option value="0">請選取倉庫</option>
            <option value="1">成品倉</option>
            <option value="2">模具倉</option>
        </select>
    </div>
    <div class="layui-inline">
        <input class="layui-input" name="id" id="demoReload" placeholder="設備編號" autocomplete="off">
    </div>
    <button class="layui-btn" data-type="reload">查詢</button>


</div>
<script type="text/html" id="switchTpERR">
    <!-- 这里的 checked 的状态只是演示 -->
    <input type="checkbox" name="ERR" value="{{d.ERR}}" lay-skin="switch" lay-text="On|" lay-filter="sexDemo" {{ d.ERR == true ? 'checked' : '' }}>
</script>

<script type="text/html" id="switchTpLoad">
    <!-- 这里的 checked 的状态只是演示 -->
    <input type="checkbox" name="LOAD" value="{{d.LOAD}}" lay-skin="switch" lay-text="On|" lay-filter="sexDemo" {{ d.LOAD == true ? 'checked' : '' }}>
</script>

<script type="text/html" id="switchTpAUTO">
    <!-- 这里的 checked 的状态只是演示 -->
    <input type="checkbox" name="AUTO" value="{{d.AUTO}}" lay-skin="switch" lay-text="On|" lay-filter="sexDemo" {{ d.AUTO == true ? 'checked' : '' }}>
</script>

<script type="text/html" id="switchTpAUTO_START">
    <!-- 这里的 checked 的状态只是演示 -->
    <input type="checkbox" name="AUTO_START" value="{{d.AUTO_START}}" lay-skin="switch" lay-text="On|" lay-filter="sexDemo" {{ d.AUTO_START == true ? 'checked' : '' }}>
</script>

<script type="text/html" id="switchTpIDLE">
    <!-- 这里的 checked 的状态只是演示 -->
    <input type="checkbox" name="IDLE" value="{{d.IDLE}}" lay-skin="switch" lay-text="On|" lay-filter="sexDemo" {{ d.IDLE == true ? 'checked' : '' }}>
</script>

<script type="text/html" id="switchTpSTKIN_REQ">
    <!-- 这里的 checked 的状态只是演示 -->
    <input type="checkbox" name="STKIN_REQ" value="{{d.STKIN_REQ}}" lay-skin="switch" lay-text="On|" lay-filter="sexDemo" {{ d.STKIN_REQ == true ? 'checked' : '' }}>
</script>

<table class="layui-hide" id="LAY_table_user" lay-filter="WcsTrk"></table>


<script src="~/layui-v2.6.8/layui/layui.js"></script>
<script>
layui.use('table', function(){
  var table = layui.table;

  //方法级渲染
  table.render({
    elem: '#LAY_table_user'
      , url: '@Url.Action("GetWcsDeviceData", "WCS")'
    ,cols: [[
        { field: 'ASRS_ID', title: '倉庫ID', width: 120, sort: true, fixed: true }
        , { field: 'DEV_NO', title: '站台', width: 80, sort: true }
        , { field: 'SER_NO', title: '序號', width: 80, sort: true }
        , { field: 'DEST', title: '目的', width: 80, sort: true }
        , { field: 'ERR', title: '異常', templet: '#switchTpERR', width: 100}
        , { field: 'LOAD', title: '有載', templet: '#switchTpLoad', width: 100}
        , { field: 'AUTO', title: '自動', templet: '#switchTpAUTO', width: 100}
        , { field: 'AUTO_START', title: '自動啟動', templet: '#switchTpAUTO_START', width: 100 }
        , { field: 'IDLE', title: '閒置', templet: '#switchTpIDLE', width: 100 }
        , { field: 'STKIN_REQ', title: '入庫要求', templet: '#switchTpSTKIN_REQ', width: 100 }
        , { field: 'IO_MODE', title: '出入庫模式', width: 120 }
        , { field: 'IN_ENABLE', title: '入庫可', width: 100 }
        , { field: 'OUT_ENABLE', title: '出庫可', width: 100 }
        , { field: 'WEIGHT', title: '秤重重量', width: 100 }
        , { field: 'SIZE_CHK', title: 'SIZE檢知', width: 110 }
        , { field: 'OP_MODE', title: '作業模式', width: 100 }
    ]]
      , id: 'tbWcsDevice'
      , page: true
      , limit: 15
      , limits:[15,20,25,30]
      , curr:1
    ,height: 'full-210'
  });

    

  var $ = layui.$, active = {
    reload: function(){
      var demoReload = $('#demoReload');

      //执行重载
          table.reload('tbWcsDevice', {
        page: {
          curr: 1 //重新从第 1 页开始
        }
        ,where: {
            SearchText: demoReload.val(),
            AsrsID: $('#cbAsrsID').val()
        }
      });
    }
  };

  $('.demoTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });


});
</script>

YakimaAsrsWeb/Views/WCS/VwStoreIn.cshtml
@{
    ViewBag.Title = "VwStoreIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/layui-v2.6.8/layui/css/layui.css" rel="stylesheet" />

<!DOCTYPE html>
<span class="layui-breadcrumb">
    @Html.ActionLink("首頁", "Index", "Home")
    <a><cite>作業管理</cite></a>
    <a><cite>入庫作業</cite></a>
</span>
<div class="layui-tab layui-tab-brief" lay-filter="docDemoTabBrief">
    <ul class="layui-tab-title">
        <li class="layui-this">空棧板入庫</li>
        <li>成品入庫</li>
        <li>模具入庫</li>
        <li>五金件入庫</li>
    </ul>
    <div class="layui-tab-content" style="height: 100px;">
        <div class="layui-tab-item layui-show">
            <form class="layui-form layui-form-pane" action="">
                <div class="layui-form-item">
                    <label class="layui-form-label">站台編號</label>
                    <div class="layui-input-inline">
                        <select name="DEV_NO" lay-verify="required">
                            <option value=""></option>
                            <option value="1182">1182</option>
                            <option value="1192">1192</option>
                            <option value="1292">1292</option>
                            <option value="1392">1392</option>
                            <option value="1492">1492</option>
                            <option value="2132">2132</option>
                            <option value="2142">2142</option>
                            <option value="2152">2152</option>
                            <option value="2232">2232</option>
                            <option value="2242">2242</option>
                            <option value="2252">2252</option>
                            <option value="2342">2342</option>
                            <option value="2352">2352</option>
                            <option value="2442">2442</option>
                            <option value="2452">2452</option>
                        </select>
                    </div>

                </div>

                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button class="layui-btn" lay-submit lay-filter="formPalletIn">提交</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="layui-tab-item">
            <form class="layui-form layui-form-pane" action="">
                <div class="layui-form-item">
                    <label class="layui-form-label">站台編號</label>
                    <div class="layui-input-inline">
                        <select name="DEV_NO" lay-verify="required">
                            <option value=""></option>
                            <option value="1182">1182</option>
                            <option value="1192">1192</option>
                            <option value="1292">1292</option>
                            <option value="1392">1392</option>
                            <option value="1492">1492</option>
                            <option value="2142">2142</option>
                            <option value="2152">2152</option>
                            <option value="2242">2242</option>
                            <option value="2252">2252</option>
                            <option value="2342">2342</option>
                            <option value="2352">2352</option>
                            <option value="2442">2442</option>
                            <option value="2452">2452</option>
                        </select>
                    </div>

                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">料號</label>
                    <div class="layui-input-inline">
                        <input type="text" name="PROD_NO" id="txtProdNo" required lay-verify="required" placeholder="請選取料號" autocomplete="off" class="layui-input">
                    </div>
                    <button class="layui-btn layui-btn-warm" onclick="OpenProductSearch()">選取</button>
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">批號</label>
                    <div class="layui-input-inline">
                        <input type="text" name="LOT_NO" autocomplete="off" class="layui-input">
                    </div>
                    <label class="layui-form-label">檢驗批號</label>
                    <div class="layui-input-inline">
                        <input type="text" name="QC_LOT" autocomplete="off" class="layui-input">
                    </div>
                    <label class="layui-form-label">數量</label>
                    <div class="layui-input-inline">
                        <input type="text" name="QTY" lay-verify="required|number" placeholder="請輸入庫存數量" autocomplete="off" class="layui-input">
                    </div>
                    <label class="layui-form-label">單位</label>
                    <div class="layui-input-inline">
                        <input type="text" name="UNITS" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <table class="layui-hide" id="TrkDet"></table>
                </div>

                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button class="layui-btn" lay-submit lay-filter="formProdIn">提交</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="layui-tab-item">内容3</div>
        <div class="layui-tab-item">内容4</div>
    </div>
</div>

<script src="~/layui-v2.6.8/layui/layui.js"></script>
<script>
//Demo
layui.use(['form','laydate','table'], function(){
    var form = layui.form;
    var laydate = layui.laydate;
    var table = layui.table;

    //执行一个laydate实例
    laydate.render({
        elem: '#txtPDate',
        type: 'date',
        format:'yyyy/MM/dd'
    });

    table.render({
        elem: '#TrkDet'        
        , cellMinWidth: 80 //全局定义常规单元格的最小宽度，layui 2.2.1 新增
        , cols: [[
            { field: 'PROD_NO', width: 120, title: '料號', sort: true }
            , { field: 'PROD_NAME', width: 250, title: '物料描述' }
        ]]
        , data: [
        ]
    });

      //监听提交
        form.on('submit(formPalletIn)', function(data){
            $.ajax({
                type: "POST",
                url: "@Url.Action("PalletIn", "WCS")",
                data: JSON.stringify(data.field),
                contentType: "application/json",
                success: function (response) {

                    JSON.stringify(response);
                    if (response.Successed) {
                        layer.msg('新增空棧板入庫作業成功~');
                    }
                    else {

                        layer.msg(response.Message, { icon: 5 });
                    }
                },
                failure: function (errMsg) {
                    layer.msg(errMsg, { icon: 5 });
                    return false;
                },
                error: function (xhr, status, err) {
                    layer.msg(err, { icon: 5 });
                }
            })
            
            console.log(data);
            return false;
        })

    //监听提交
    form.on('submit(formProdIn)', function(data){
        @*$.ajax({
            type: "POST",
            url: "@Url.Action("ProdIn", "WCS")",
            data: JSON.stringify(data.field),
            contentType: "application/json",
            success: function (response) {

                JSON.stringify(response);
                if (response.Successed) {
                    layer.msg('新增成品入庫作業成功~');
                }
                else {

                    layer.msg(response.Message, { icon: 5 });
                }
            },
            failure: function (errMsg) {
                layer.msg(errMsg, { icon: 5 });
                return false;
            },
            error: function (xhr, status, err) {
                layer.msg(err, { icon: 5 });
            }
        })*@
        console.log(data);
        return false;
    })

    });

    function OpenProductSearch() {
        layer.open({
            type: 2,
            area: ['700px', '600px'],
            fixed: false, //不固定
            maxmin: true,
            title: '選取料號',
            btn: ['確定','取消'],
            content: '@Url.Action("VwProdList","WMS")',
            yes: function (index) {
                var result = window["layui-layer-iframe" + index].returndata();
                if (result != null) {
                    //layer.msg(result.ProdNo);
                    document.getElementById("txtProdNo").value = result.ProdNo;
                    //document.getElementById("divProdName").innerHTML = result.ProdName;
                    layer.close(index);
                }
                else {
                    layer.msg('No Data');
                }
            }
        });
    }

</script>