YakimaAsrsWeb/Controllers/WMSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YakimaAsrsWeb.Extensions;
using YakimaAsrsWeb.Filters;

namespace YakimaAsrsWeb.Controllers
{
    [CustomAuthenticationFilter]
    public class WMSController : Controller
    {
        Service.WmsStkService StkService = new Service.WmsStkService();
        Service.WmsBinStaService BinStaService = new Service.WmsBinStaService();

        class UIDropDown
        {
            public string Text { get; set; }
            public object Value { get; set; }
        }

        // GET: STK View
        public ActionResult VwStk()
        {
            return View();
        }

        // GET: BinSta View
        public ActionResult VwBinSta()
        {
            return View();
        }

        public ActionResult VwAddWmsStk()
        {
            //var ProdList = StkService.GetProdListData();
            //if (ProdList.IsCompleted)
            //{
            //    List<Models.WmsProd> Prods = new List<Models.WmsProd>();
            //    foreach (DataRow dr in ProdList.Result.Data.Rows)
            //    {
            //        Prods.Add(new Models.WmsProd() { ProdNo = dr["PROD_NO"].ToString(), ProdName = dr["PROD_NAME"].ToString() });
            //    }
            //    ViewBag.ProdList = new SelectList(
            //        items: Prods,
            //        dataTextField: "ProdName",
            //        dataValueField: "ProdNo"
            //        );
                
            //}
            return View();
        }

        public ActionResult VwProdList()
        {
            return View();
        }

        public JsonResult GetWmsProdData(string SearchText, int? Page, int? Limit)
        {
            List<Models.WmsProd> Prods = new List<Models.WmsProd>();
            Models.LayUITableData result = new Models.LayUITableData();
            var DataResult = StkService.GetProdListData(SearchText);
           
            if (DataResult.IsCompleted)
            {
                if (DataResult.Result.Successed)
                {
                    foreach (System.Data.DataRow dr in DataResult.Result.Data.Rows)
                    {
                        Prods.Add(new Models.WmsProd()
                        {
                            ProdNo = Convert.ToString(dr["PROD_NO"]),
                            ProdName = Convert.ToString(dr["PROD_NAME"])

                        });
                    }

                    //if (!string.IsNullOrEmpty(SearchText))
                    //{
                    //    Prods = Prods.Where(o => o.ProdNo.Contains(SearchText)
                    //    || o.ProdName.Contains(SearchText)
                    //    ).ToList();
                    //}
                    result.count = Prods.Count;

                    result.data = Prods;
                    result.code = 0;
                }
                else
                {
                    result.count = 0;

                    result.data = Prods;
                    result.code = Convert.ToInt16(HttpStatusCode.InternalServerError);
                }
            }

            result.data = Prods.Skip((Page.Value - 1) * Limit.Value).Take(Limit.Value);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetWmsStkData(string SearchText, int? AsrsID, int? ProdType, int? StusCtr, int? Page, int? Limit)
        {
            Models.LayUITableData result = new Models.LayUITableData();
            var DataResult = StkService.GetData();
            List<Models.WmsStk> Stks = new List<Models.WmsStk>();
            if (DataResult.IsCompleted)
            {
                if (DataResult.Result.Successed)
                {
                    foreach (System.Data.DataRow dr in DataResult.Result.Data.Rows)
                    {
                        Stks.Add(new Models.WmsStk()
                        {
                            ASRS_ID = Convert.ToInt16(dr["ASRS_ID"]),
                            AREA = Convert.ToString(dr["AREA"]),
                            AREA_NO = Convert.ToString(dr["AREA_NO"]),
                            WH_NO = Convert.ToString(dr["WH_NO"]),
                            FIFO_NO = Convert.ToString(dr["FIFO_NO"]),
                            BIN_NO = Convert.ToString(dr["BIN_NO"]),
                            STUS_CTR_DESC = Convert.ToString(dr["STUS_CTR_DESC"]),
                            PROD_NO = Convert.ToString(dr["PROD_NO"]),
                            PROD_NAME = Convert.ToString(dr["PROD_NAME"]),
                            PROD_TYPE_DESC = Convert.ToString(dr["PROD_TYPE_DESC"]),
                            LOT_NO = Convert.ToString(dr["LOT_NO"]),
                            QC_LOT = Convert.ToString(dr["QC_LOT"]),
                            SCHEDULE_REMARK = Convert.ToString(dr["SCHEDULE_REMARK"]),
                            SRC_BIN_NO = Convert.ToString(dr["SRC_BIN_NO"]),
                            SUPPLIER = Convert.ToString(dr["SUPPLIER"]),
                            UNITS = Convert.ToString(dr["UNITS"]),
                            AUFNR = Convert.ToString(dr["AUFNR"]),
                            VORNR = Convert.ToString(dr["VORNR"]),
                            VORNR_NEXT = Convert.ToString(dr["VORNR_NEXT"]),
                            MOLD_NO = Convert.ToString(dr["MOLD_NO"]),
                            MOLD_GROUP = Convert.ToString(dr["MOLD_GROUP"]),
                            MOLD_STATUS = Convert.ToString(dr["MOLD_STATUS"]),
                            EBPM_NO = Convert.ToString(dr["EBPM_NO"]),
                            LIST_NO = Convert.ToString(dr["LIST_NO"]),
                            REMARK = Convert.ToString(dr["REMARK"]),
                            M_WIP_NO = Convert.ToString(dr["M_WIP_NO"]),
                            QTY = Convert.ToDecimal(dr["QTY"]),
                            LINE_ID = Convert.IsDBNull(dr["LINE_ID"]) ? null : (decimal?)dr["LINE_ID"],
                            PROD_TYPE = Convert.ToDecimal(dr["PROD_TYPE"]),
                            MOVE_OPN = dr["MOVE_OPN"].ToString(),
                            RES_QTY = Convert.IsDBNull(dr["RES_QTY"]) ? null : (decimal?)dr["RES_QTY"],
                            STUS_CTR = Convert.ToDecimal(dr["STUS_CTR"]),
                            STOREIN_DATE = Convert.ToDateTime(dr["STOREIN_DATE"]).ToString("yyyy/MM/dd"),
                            PDATE = Convert.IsDBNull(dr["PDATE"]) ? null : ((DateTime)dr["PDATE"]).ToString("yyyy/MM/dd")

                        });
                    }

                    if (AsrsID.HasValue)
                    {
                        if (AsrsID > 0)
                            Stks = Stks.Where(o => o.ASRS_ID == AsrsID).ToList();
                    }
                    
                    if (ProdType.HasValue)
                    {
                        if (ProdType >= 0)
                            Stks = Stks.Where(o => o.PROD_TYPE == ProdType).ToList();
                    }

                    if (StusCtr.HasValue)
                    {
                        if (StusCtr >= 0)
                            Stks = Stks.Where(o => o.STUS_CTR == StusCtr).ToList();
                    }

                    if (!string.IsNullOrEmpty(SearchText))
                    {
                        Stks = Stks.Where(o => o.PROD_NO.Contains(SearchText)
                        || o.PROD_NAME.Contains(SearchText)
                        || o.BIN_NO.Contains(SearchText)
                        || o.LOT_NO.Contains(SearchText)
                        || o.QC_LOT.Contains(SearchText)
                        || o.REMARK.Contains(SearchText)
                        || o.STUS_CTR_DESC.Contains(SearchText)
                        || o.PROD_TYPE_DESC.Contains(SearchText)
                        || o.REMARK.Contains(SearchText)
                        || o.MOLD_NO.Contains(SearchText)
                        ).ToList();
                    }
                    result.count = Stks.Count;

                    result.data = Stks;
                    result.code = 0;
                }
                else
                {
                    result.count = 0;

                    result.data = Stks;
                    result.code = Convert.ToInt16(HttpStatusCode.InternalServerError);
                }
            }

            result.data = Stks.Skip((Page.Value - 1) * Limit.Value).Take(Limit.Value);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetWmsBinstaData(string SearchText, int? AsrsID, string BinSta, int? Page, int? Limit)
        {
            Models.LayUITableData result = new Models.LayUITableData();
            var DataResult = BinStaService.GetData();
            List<Models.WmsBinsta> BinStas = new List<Models.WmsBinsta>();
            if (DataResult.IsCompleted)
            {
                if (DataResult.Result.Successed)
                {
                    foreach (System.Data.DataRow dr in DataResult.Result.Data.Rows)
                    {
                        BinStas.Add(new Models.WmsBinsta()
                        {
                            ASRS_ID = Convert.ToInt16(dr["ASRS_ID"]),
                            AREA = Convert.ToString(dr["AREA"]),
                            AREA_NO = Convert.ToString(dr["AREA_NO"]),
                            WH_NO = Convert.ToString(dr["WH_NO"]),
                            BIN_NO = Convert.ToString(dr["BIN_NO"]),
                            BIN_STA = Convert.ToString(dr["BIN_STA"]),
                            BIN_STA_DESC = Convert.ToString(dr["BIN_STA_DESC"]),
                            INHIBIT_IN_FLG = Convert.ToString(dr["INHIBIT_IN_FLG"]),
                            INHIBIT_OUT_FLG = Convert.ToString(dr["INHIBIT_OUT_FLG"]),
                            SIZE_CHK = Convert.ToString(dr["SIZE_CHK"])

                        });

YakimaAsrsWeb/Views/WMS/VwAddWmsStk.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<link href="~/layui-v2.6.8/layui/css/layui.css" rel="stylesheet" />

<br />

<div class="layui-form">
    <div class="layui-form-item">
        <label class="layui-form-label">倉別</label>
        <div class="layui-input-inline">
            <select name="ASRS_ID" lay-verify="required">
                <option value=""></option>
                <option value="1">成品倉</option>
                <option value="2">半成品/模具倉</option>
            </select>
        </div>
        <label class="layui-form-label">儲區</label>
        <div class="layui-input-inline">
            <select name="WH_NO" lay-verify="required">
                <option value=""></option>
                <option value="A">自動倉</option>
                <option value="P">撿料倉</option>
                <option value="C">併板倉</option>
            </select>
        </div>

        <label class="layui-form-label">庫位</label>
        <div class="layui-input-inline">
            <input type="text" name="BIN_NO" required lay-verify="required" placeholder="請輸入庫位" autocomplete="off" class="layui-input">
        </div>

    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">庫存類型</label>
        <div class="layui-input-inline">
            <select name="PROD_TYPE" lay-verify="required">
                <option value=""></option>
                <option value="0">成品/原物料</option>
                <option value="1">五金加工件</option>
                <option value="2">模具</option>
                <option value="3">載具</option>
                <option value="4">暫存品</option>
            </select>
        </div>
        <label class="layui-form-label">庫存狀態</label>
        <div class="layui-input-inline">
            <select name="PROD_TYPE" lay-verify="required" lay-search>
                <option value=""></option>
                <option value="0">在庫</option>
                <option value="100">工作檔入庫預約</option>
                <option value="101">工作檔出庫預約</option>
                <option value="2">撿料待回庫</option>
                <option value="3">模具待回庫</option>
                <option value="4">盤點待回庫</option>
                <option value="5">庫存待驗</option>
                <option value="6">工單領料鎖定</option>
                <option value="7">併板待回庫</option>
                <option value="8">模具庫外待使用</option>
                <option value="9">模具待繳回</option>
                <option value="10">五金待回庫</option>
            </select>
        </div>

        @*<label class="layui-form-label">料號</label>
            <div class="layui-input-inline">
                @Html.DropDownList("ProdList", null, "請選擇", new { @id = "ProdList", @name = "ProdList", lay_search = "" })
            </div>
            <div class="layui-form-mid layui-word-aux">辅助文字</div>*@

        <label class="layui-form-label">料號</label>
        <div class="layui-input-inline">
            <input type="text" name="PROD_NO" id="txtProdNo" required lay-verify="required" placeholder="請選取料號" autocomplete="off" class="layui-input">
        </div>
        <button class="layui-btn layui-btn-warm" onclick="OpenProductSearch()">選取</button>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">批號</label>
        <div class="layui-input-inline">
            <input type="text" name="LOT_NO" autocomplete="off" class="layui-input">
        </div>
        <label class="layui-form-label">數量</label>
        <div class="layui-input-inline">
            <input type="text" name="QTY" lay-verify="required|number" placeholder="請輸入庫存數量" autocomplete="off" class="layui-input">
        </div>
        <label class="layui-form-label">單位</label>
        <div class="layui-input-inline">
            <input type="text" name="UNITS" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">

        <label class="layui-form-label">生產日期</label>
        <div class="layui-input-inline">
            <input type="text" name="PDATE" placeholder="請選取生產日期" class="layui-input" id="txtPDate">
        </div>
        <label class="layui-form-label">檢驗批號</label>
        <div class="layui-input-inline">
            <input type="text" name="QC_LOT" autocomplete="off" class="layui-input">
        </div>

    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">工單</label>
        <div class="layui-input-inline">
            <input type="text" name="AUFNR" autocomplete="off" class="layui-input">
        </div>
        <label class="layui-form-label">工序</label>
        <div class="layui-input-inline">
            <input type="text" name="VORNR" autocomplete="off" class="layui-input">
        </div>
        <label class="layui-form-label">下一工序</label>
        <div class="layui-input-inline">
            <input type="text" name="VORNR_NEXT" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">模具編號</label>
        <div class="layui-input-inline">
            <input type="text" name="MOLD_NO" autocomplete="off" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <label class="layui-form-label">模具狀態</label>
        <div class="layui-input-inline">
            <select name="MOLD_STATUS" lay-search>
                <option value=""></option>
                <option value="0">無狀態</option>
                <option value="1">在庫</option>
                <option value="2">工單領用</option>
                <option value="3">保養</option>
                <option value="4">維修</option>
                <option value="5">移轉至平面倉</option>
                <option value="6">報廢</option>
                <option value="7">試模</option>
                <option value="8">盤點中</option>
                <option value="9">遺失</option>
                <option value="A">改模</option>
                <option value="B">委外</option>
                <option value="C">出售</option>
                <option value="D">餘模待回庫</option>
                <option value="E">併板待回庫</option>
                <option value="F">借用</option>
                <option value="G">閒置</option>
            </select>
        </div>

    </div>

    <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">備註</label>
        <div class="layui-input-block">
            <textarea name="REMARK" placeholder="請輸入備註" class="layui-textarea"></textarea>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>
</div>

<script src="~/layui-v2.6.8/layui/layui.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
//Demo
layui.use(['form','laydate'], function(){
    var form = layui.form;
    var laydate = layui.laydate;

    //执行一个laydate实例
    laydate.render({
        elem: '#txtPDate',
        type: 'date',
        format:'yyyy/MM/dd'
    });

      //监听提交
      form.on('submit(formDemo)', function(data){
        //layer.msg(JSON.stringify(data.field));
          //Post Command
          PostAdd(JSON.stringify(data.field));

        return false;
      });
    });

    function OpenProductSearch() {
        layer.open({
            type: 2,
            area: ['700px', '600px'],
            fixed: false, //不固定
            maxmin: true,
            title: '選取料號',
            btn: ['確定','取消'],
            content: '@Url.Action("VwProdList","WMS")',
            yes: function (index) {
                var result = window["layui-layer-iframe" + index].returndata();
                if (result != null) {
                    //layer.msg(result.ProdNo);
                    document.getElementById("txtProdNo").value = result.ProdNo;
                    //document.getElementById("divProdName").innerHTML = result.ProdName;
                    layer.close(index);
                }
                else {
                    layer.msg('No Data');
                }
            }
        });
    }

    function PostAdd(data) {
        $.ajax({
            type: "POST",
            url: "@Url.Action("AddWmsStk", "WMS")",
            data: data,
            contentType: "application/json",
            success: function (response) {

                JSON.stringify(response);
                if (response.Successed) {

                    layer.msg('新增庫存資料成功~');
                }
                else {

                    layer.msg(response.Message, { icon: 5 });
                }
            },
            failure: function (errMsg) {
                layer.msg(errMsg, { icon: 5 });
                return false;
            },
            error: function (xhr, status, err) {
                layer.msg(err, { icon: 5 });
            }
        })
    }
</script>

YakimaAsrsWeb/Views/WMS/VwBinSta.cshtml
@{
    ViewBag.Title = "庫位狀態查詢維護";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<span class="layui-breadcrumb">
    @Html.ActionLink("首頁", "Index", "Home")
    <a><cite>庫存管理</cite></a>
    <a><cite>@ViewBag.Title</cite></a>
</span>
<hr />

<div class="demoTable">

    <div class="layui-form layui-input-inline">
        <select name="AsrsID" id="cbAsrsID">
            <option value="0">請選取倉庫</option>
            <option value="1">成品倉</option>
            <option value="2">模具倉</option>
        </select>
    </div>
    <div class="layui-form layui-input-inline">
        <select name="BinSta" id="cbBinSta">
            <option value="">庫位狀態</option>
            <option value="_">空庫</option>
            <option value="$">庫存庫位</option>
            <option value="?">先入品</option>
            <option value="O">出庫中</option>
            <option value="I">入庫中</option>
        </select>
    </div>
    <div class="layui-inline">
        <input class="layui-input" name="id" id="demoReload" placeholder="模糊查詢" autocomplete="off">
    </div>
    <button class="layui-btn " data-type="reload">查詢</button>


</div>


<table class="layui-hide" id="LAY_table_user" lay-filter="WcsTrk"></table>

<script type="text/html" id="DisableInTpl">
    {{#  if(d.INHIBIT_IN_FLG === 'Y'){ }}
    <span style="color: #d9534f;">{{ '是' }}</span>
    {{#  } else { }}
    {{ '否' }}
    {{#  } }}
</script>

<script type="text/html" id="DisableOutTpl">
    {{#  if(d.INHIBIT_OUT_FLG === 'Y'){ }}
    <span style="color: #d9534f;">{{ '是' }}</span>
    {{#  } else { }}
    {{ '否' }}
    {{#  } }}
</script>

<script type="text/html" id="barDemo">
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="btnEmpty">轉空庫</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="btnPreload">轉先入品</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="btnStk">轉庫存庫位</a>
</script>

<script src="~/layui-v2.6.8/layui/layui.js"></script>
<script>
layui.use('table', function(){
  var table = layui.table;

  //方法级渲染
  table.render({
    elem: '#LAY_table_user'
    , url: '@Url.Action("GetWmsBinstaData", "WMS")'
    ,cols: [[
        { field: 'ASRS_ID', title: '倉庫ID', width: 100, sort: true, fixed: true, align: 'right' }
        , { field: 'WH_NO', title: '儲區', width: 80, sort: true, fixed: true }
        , { field: 'BIN_NO', title: '庫位', width: 90, sort: true, fixed: true}
        , { field: 'BIN_STA', title: '庫位狀態', width: 110, sort: true}
        , { field: 'BIN_STA_DESC', title: '說明', width: 120, sort: true}
        , { field: 'AREA', title: '材積率', width: 110, sort: true, align: 'right'}
        , { field: 'SIZE_CHK', title: '庫位高低尺寸', width: 130, sort: true, align: 'right'}
        , { field: 'INHIBIT_IN_FLG', title: '禁入', width: 100, sort: true, templet: '#DisableInTpl' }
        , { field: 'INHIBIT_OUT_FLG', title: '禁出', width: 100, sort: true, templet: '#DisableOutTpl' }
        , { fixed: 'right', title: '操作', toolbar: '#barDemo', width: 250 }
    ]]
      , id: 'tbWmsBinSta'
      , page: true
      , limit: 15
      , limits:[15,20,25,30]
      , curr:1
      , height: 'full-210'
      , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
      , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
          title: '提示'
          , layEvent: 'LAYTABLE_TIPS'
          , icon: 'layui-icon-tips'
      }]
  });



  var $ = layui.$, active = {
    reload: function(){
      var demoReload = $('#demoReload');

      //执行重载
          table.reload('tbWmsBinSta', {
        page: {
          curr: 1 //重新从第 1 页开始
        }
        ,where: {
            SearchText: demoReload.val(),
            AsrsID: $('#cbAsrsID').val(),
            BinSta: $('#cbBinSta').val()
        }
      });
    }
  };

  $('.demoTable .layui-btn').on('click', function(){
    var type = $(this).data('type');
    active[type] ? active[type].call(this) : '';
  });


});
</script>

YakimaAsrsWeb/Views/WMS/VwProdList.cshtml
@{
    Layout = null;
}
<link href="~/layui-v2.6.8/layui/css/layui.css" rel="stylesheet" />

<div class="demoTable">

    <div class="layui-inline">
        <input class="layui-input" name="id" id="demoReload" placeholder="模糊查詢" autocomplete="off">
    </div>
    <button class="layui-btn" data-type="reload">查詢</button>


</div>

<table class="layui-hide" id="tbWmsPord" lay-filter="WmsProd"></table>

<script src="~/layui-v2.6.8/layui/layui.js"></script>

<script type="text/javascript">
    var SelectedItem = {};
    layui.use('table', function(){
      var table = layui.table;

      //方法级渲染
      table.render({
          elem: '#tbWmsPord'
          , url: '@Url.Action("GetWmsProdData", "WMS")'
          , cols: [[
              { field: 'ProdNo', title: '料號', width: 250, sort: true, filter: true }
              , { field: 'ProdName', title: '物料描述', width: 350, sort: true, filter: true }
        ]]
          , id: 'tbWmsPord'
          , page: true
          , limit: 15
          , limits:[15,20,25,30]
          , curr:1
          , height: 'full'
      
      });

        table.on('row(WmsProd)', function (obj) {
            obj.tr.addClass('layui-bg-cyan').siblings().removeClass('layui-bg-cyan');
            SelectedItem.ProdNo = obj.data.ProdNo;
            SelectedItem.ProdName = obj.data.ProdName;
            
        });


        var $ = layui.$, active = {
            reload: function () {
                var demoReload = $('#demoReload');

                //执行重载
                table.reload('tbWmsPord', {
                    page: {
                        curr: 1 //重新从第 1 页开始
                    }
                    , where: {
                        SearchText: demoReload.val()
                    }
                });
            }
        };

        $('.demoTable .layui-btn').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });

    });
    function returndata() {
        return SelectedItem;
    };

    
</script>